/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Utilisateur
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        cardLayout = (CardLayout)(Parent.getLayout());
    }
    
    CardLayout cardLayout;
    public void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btn_accueil = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_enregistrer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_stock = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_approv = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_vendre = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_modif = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_quit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        Accueil = new javax.swing.JPanel();
        Enregistrer = new javax.swing.JPanel();
        Stock = new javax.swing.JPanel();
        Approv = new javax.swing.JPanel();
        Vendre = new javax.swing.JPanel();
        ModifSuppr = new javax.swing.JPanel();
        Quitter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_accueil.setBackground(new java.awt.Color(85, 65, 118));
        btn_accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_accueilMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8_home_26px_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Accueil");

        javax.swing.GroupLayout btn_accueilLayout = new javax.swing.GroupLayout(btn_accueil);
        btn_accueil.setLayout(btn_accueilLayout);
        btn_accueilLayout.setHorizontalGroup(
            btn_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_accueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_accueilLayout.setVerticalGroup(
            btn_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_accueilLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.add(btn_accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, -1));

        btn_enregistrer.setBackground(new java.awt.Color(64, 43, 100));
        btn_enregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_enregistrerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_enregistrerMousePressed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8_data_recovery_25px_2.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Enregistrer Article");

        javax.swing.GroupLayout btn_enregistrerLayout = new javax.swing.GroupLayout(btn_enregistrer);
        btn_enregistrer.setLayout(btn_enregistrerLayout);
        btn_enregistrerLayout.setHorizontalGroup(
            btn_enregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_enregistrerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_enregistrerLayout.setVerticalGroup(
            btn_enregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_enregistrerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(btn_enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, -1));

        btn_stock.setBackground(new java.awt.Color(64, 43, 100));
        btn_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_stockMousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8_shopping_cart_25px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Stock");

        javax.swing.GroupLayout btn_stockLayout = new javax.swing.GroupLayout(btn_stock);
        btn_stock.setLayout(btn_stockLayout);
        btn_stockLayout.setHorizontalGroup(
            btn_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_stockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_stockLayout.setVerticalGroup(
            btn_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_stockLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.add(btn_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, -1));

        btn_approv.setBackground(new java.awt.Color(64, 43, 100));
        btn_approv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_approvMousePressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8_add_26px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Approvisionner");

        javax.swing.GroupLayout btn_approvLayout = new javax.swing.GroupLayout(btn_approv);
        btn_approv.setLayout(btn_approvLayout);
        btn_approvLayout.setHorizontalGroup(
            btn_approvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_approvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_approvLayout.setVerticalGroup(
            btn_approvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_approvLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.add(btn_approv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, -1));

        btn_vendre.setBackground(new java.awt.Color(64, 43, 100));
        btn_vendre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vendreMousePressed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8_sell_26px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Vendre");

        javax.swing.GroupLayout btn_vendreLayout = new javax.swing.GroupLayout(btn_vendre);
        btn_vendre.setLayout(btn_vendreLayout);
        btn_vendreLayout.setHorizontalGroup(
            btn_vendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_vendreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_vendreLayout.setVerticalGroup(
            btn_vendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_vendreLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.add(btn_vendre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, -1));

        btn_modif.setBackground(new java.awt.Color(64, 43, 100));
        btn_modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_modifMousePressed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8_Delete_26px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Modifier/Supprimer");

        javax.swing.GroupLayout btn_modifLayout = new javax.swing.GroupLayout(btn_modif);
        btn_modif.setLayout(btn_modifLayout);
        btn_modifLayout.setHorizontalGroup(
            btn_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_modifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_modifLayout.setVerticalGroup(
            btn_modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_modifLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.add(btn_modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 260, -1));

        btn_quit.setBackground(new java.awt.Color(64, 43, 100));
        btn_quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_quitMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/icons8_sign_out_26px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Quitter");

        javax.swing.GroupLayout btn_quitLayout = new javax.swing.GroupLayout(btn_quit);
        btn_quit.setLayout(btn_quitLayout);
        btn_quitLayout.setHorizontalGroup(
            btn_quitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_quitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_quitLayout.setVerticalGroup(
            btn_quitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_quitLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.add(btn_quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 260, -1));

        Parent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout AccueilLayout = new javax.swing.GroupLayout(Accueil);
        Accueil.setLayout(AccueilLayout);
        AccueilLayout.setHorizontalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        AccueilLayout.setVerticalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        Parent.add(Accueil, "card2");

        javax.swing.GroupLayout EnregistrerLayout = new javax.swing.GroupLayout(Enregistrer);
        Enregistrer.setLayout(EnregistrerLayout);
        EnregistrerLayout.setHorizontalGroup(
            EnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        EnregistrerLayout.setVerticalGroup(
            EnregistrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        Parent.add(Enregistrer, "card3");

        javax.swing.GroupLayout StockLayout = new javax.swing.GroupLayout(Stock);
        Stock.setLayout(StockLayout);
        StockLayout.setHorizontalGroup(
            StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        StockLayout.setVerticalGroup(
            StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        Parent.add(Stock, "card4");

        javax.swing.GroupLayout ApprovLayout = new javax.swing.GroupLayout(Approv);
        Approv.setLayout(ApprovLayout);
        ApprovLayout.setHorizontalGroup(
            ApprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        ApprovLayout.setVerticalGroup(
            ApprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        Parent.add(Approv, "card5");

        javax.swing.GroupLayout VendreLayout = new javax.swing.GroupLayout(Vendre);
        Vendre.setLayout(VendreLayout);
        VendreLayout.setHorizontalGroup(
            VendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        VendreLayout.setVerticalGroup(
            VendreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        Parent.add(Vendre, "card6");

        javax.swing.GroupLayout ModifSupprLayout = new javax.swing.GroupLayout(ModifSuppr);
        ModifSuppr.setLayout(ModifSupprLayout);
        ModifSupprLayout.setHorizontalGroup(
            ModifSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        ModifSupprLayout.setVerticalGroup(
            ModifSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        Parent.add(ModifSuppr, "card7");

        javax.swing.GroupLayout QuitterLayout = new javax.swing.GroupLayout(Quitter);
        Quitter.setLayout(QuitterLayout);
        QuitterLayout.setHorizontalGroup(
            QuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        QuitterLayout.setVerticalGroup(
            QuitterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        Parent.add(Quitter, "card8");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accueilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accueilMousePressed
        // TODO add your handling code here:
        setColor(btn_accueil);
        resetColor(btn_enregistrer);
        resetColor(btn_stock);
        resetColor(btn_approv);
        resetColor(btn_vendre);
        resetColor(btn_modif);
        resetColor(btn_quit);
    }//GEN-LAST:event_btn_accueilMousePressed

    private void btn_enregistrerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enregistrerMousePressed
        // TODO add your handling code here:
        setColor(btn_enregistrer);
        resetColor(btn_stock);
        resetColor(btn_approv);
        resetColor(btn_vendre);
        resetColor(btn_modif);
        resetColor(btn_quit);
        resetColor(btn_accueil);
    }//GEN-LAST:event_btn_enregistrerMousePressed

    private void btn_stockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMousePressed
        // TODO add your handling code here:
        setColor(btn_stock);
        resetColor(btn_approv);
        resetColor(btn_vendre);
        resetColor(btn_modif);
        resetColor(btn_quit);
        resetColor(btn_accueil);
        resetColor(btn_enregistrer);
             
    }//GEN-LAST:event_btn_stockMousePressed

    private void btn_approvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_approvMousePressed
        // TODO add your handling code here:
        setColor(btn_approv);
        resetColor(btn_vendre);
        resetColor(btn_modif);
        resetColor(btn_quit);
        resetColor(btn_accueil);
        resetColor(btn_enregistrer);
        resetColor(btn_stock);
    }//GEN-LAST:event_btn_approvMousePressed

    private void btn_vendreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vendreMousePressed
        // TODO add your handling code here:
        setColor(btn_vendre);
        resetColor(btn_modif);
        resetColor(btn_quit);
        resetColor(btn_accueil);
        resetColor(btn_enregistrer);
        resetColor(btn_stock);
        resetColor(btn_approv);
    }//GEN-LAST:event_btn_vendreMousePressed

    private void btn_modifMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modifMousePressed
        // TODO add your handling code here:
        setColor(btn_modif);
        resetColor(btn_quit);
        resetColor(btn_accueil);
        resetColor(btn_enregistrer);
        resetColor(btn_stock);
        resetColor(btn_approv);
        resetColor(btn_vendre);
    }//GEN-LAST:event_btn_modifMousePressed

    private void btn_quitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quitMousePressed
        // TODO add your handling code here:
        setColor(btn_quit);
        resetColor(btn_accueil);
        resetColor(btn_enregistrer);
        resetColor(btn_stock);
        resetColor(btn_approv);
        resetColor(btn_vendre);
        resetColor(btn_modif);
    }//GEN-LAST:event_btn_quitMousePressed

    private void btn_enregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enregistrerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_enregistrerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JPanel Approv;
    private javax.swing.JPanel Enregistrer;
    private javax.swing.JPanel ModifSuppr;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel Quitter;
    private javax.swing.JPanel Stock;
    private javax.swing.JPanel Vendre;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_accueil;
    private javax.swing.JPanel btn_approv;
    private javax.swing.JPanel btn_enregistrer;
    private javax.swing.JPanel btn_modif;
    private javax.swing.JPanel btn_quit;
    private javax.swing.JPanel btn_stock;
    private javax.swing.JPanel btn_vendre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
